"""add news_article_matches table

Revision ID: 3d0c6d4e219e
Revises: 5269b93b6f9b
Create Date: 2026-07-31 12:51:53.579151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d0c6d4e219e'
down_revision: Union[str, None] = '5269b93b6f9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_article_matches',
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('relevance', sa.Float(), nullable=True),
    sa.Column('match_source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('news_id <> article_id', name='ck_news_article_matches_not_self'),
    sa.ForeignKeyConstraint(['article_id'], ['analysis_article.news_id'], ),
    sa.ForeignKeyConstraint(['news_id'], ['news.news_id'], ),
    sa.PrimaryKeyConstraint('news_id', 'article_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news_article_matches')
    # ### end Alembic commands ###
