"""add tag_category_rules and news_company_link.match_source

Revision ID: 5269b93b6f9b
Revises: 5309aeb50bad
Create Date: 2026-07-30 23:42:15.287350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5269b93b6f9b'
down_revision: Union[str, None] = '5309aeb50bad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag_category_rules',
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('target_field', sa.String(length=20), nullable=False),
    sa.Column('target_value', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.tag_id'], ),
    sa.PrimaryKeyConstraint('rule_id'),
    sa.UniqueConstraint('tag_id', 'target_field', 'target_value', name='uq_tag_category_rule')
    )
    op.add_column(
        'news_company_link',
        sa.Column('match_source', sa.String(length=20), nullable=False, server_default='direct_mention'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_company_link', 'match_source')
    op.drop_table('tag_category_rules')
    # ### end Alembic commands ###
