"""add industry and company detail tables

Revision ID: 768c693cda66
Revises: c4b9d57c2bc5
Create Date: 2026-07-26 16:25:28.551209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '768c693cda66'
down_revision: Union[str, None] = 'c4b9d57c2bc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industries',
    sa.Column('industry_id', sa.Integer(), nullable=False),
    sa.Column('industry_name', sa.String(length=100), nullable=False),
    sa.Column('parent_industry_id', sa.Integer(), nullable=True),
    sa.Column('sector_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_industry_id'], ['industries.industry_id'], ),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.sector_id'], ),
    sa.PrimaryKeyConstraint('industry_id')
    )
    op.create_table('competitors',
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('competitor_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('competitor_id')
    )
    op.create_table('governmental_programs_and_regulations',
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('program_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('program_id')
    )
    op.create_table('legal_and_regulatory_issues',
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('issue_title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('issue_id')
    )
    op.create_table('management_discussions_and_analyses',
    sa.Column('mdna_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('mdna_title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('mdna_id')
    )
    op.create_table('manufacturing_processes',
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('process_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('process_id')
    )
    op.create_table('risks',
    sa.Column('risk_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('risk_type', sa.Enum('financial', 'operational', 'strategic', 'compliance', 'reputational', 'market', 'other', name='risk_type_enum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('risk_id')
    )
    op.create_table('services',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('service_id')
    )
    op.create_table('supply_chains_and_logistics',
    sa.Column('supply_chain_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('supply_chain_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('supply_chain_id')
    )
    op.create_table('technologies',
    sa.Column('technology_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('technology_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('technology_id')
    )
    op.add_column('companies', sa.Column('industry_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'companies', 'industries', ['industry_id'], ['industry_id'])
    op.add_column('news', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'description')
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_column('companies', 'industry_id')
    op.drop_table('technologies')
    op.drop_table('supply_chains_and_logistics')
    op.drop_table('services')
    op.drop_table('risks')
    op.drop_table('manufacturing_processes')
    op.drop_table('management_discussions_and_analyses')
    op.drop_table('legal_and_regulatory_issues')
    op.drop_table('governmental_programs_and_regulations')
    op.drop_table('competitors')
    op.drop_table('industries')
    # ### end Alembic commands ###
