"""add content_hash index to company_fact_embeddings

Revision ID: 8605294e1ce3
Revises: abc3e61724a7
Create Date: 2026-07-30 10:35:44.429653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8605294e1ce3'
down_revision: Union[str, None] = 'abc3e61724a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_company_fact_embeddings_content_hash', 'company_fact_embeddings', ['content_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_company_fact_embeddings_content_hash', table_name='company_fact_embeddings')
    # ### end Alembic commands ###
