"""adding concept, conceptRelation and conceptRelationEvidence

Revision ID: 098388f0d34a
Revises: 528fae4bb566
Create Date: 2026-08-06 20:57:09.046188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '098388f0d34a'
down_revision: Union[str, None] = '528fae4bb566'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concepts',
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('concept_type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('aliases', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('concept_id'),
    sa.UniqueConstraint('company_id', name='uq_concepts_company_id')
    )
    op.create_table('concept_relations',
    sa.Column('relation_id', sa.Integer(), nullable=False),
    sa.Column('from_concept_id', sa.Integer(), nullable=False),
    sa.Column('to_concept_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=False),
    sa.Column('polarity', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reinforcement_count', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_reinforced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_reviewed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_concept_id'], ['concepts.concept_id'], ),
    sa.ForeignKeyConstraint(['to_concept_id'], ['concepts.concept_id'], ),
    sa.PrimaryKeyConstraint('relation_id'),
    sa.UniqueConstraint('from_concept_id', 'to_concept_id', 'relation_type', 'polarity', name='uq_concept_relations_edge')
    )
    op.create_table('concept_relation_evidence',
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('relation_id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news.news_id'], ),
    sa.ForeignKeyConstraint(['relation_id'], ['concept_relations.relation_id'], ),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('concept_relation_evidence')
    op.drop_table('concept_relations')
    op.drop_table('concepts')
    # ### end Alembic commands ###
