"""nullable company_id on embeddings, add is_primary to link tables

Revision ID: 5309aeb50bad
Revises: 8605294e1ce3
Create Date: 2026-07-30 22:58:46.744887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5309aeb50bad'
down_revision: Union[str, None] = '8605294e1ce3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'analysis_article_company_link',
        sa.Column('is_primary', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('company_fact_embeddings', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column(
        'news_company_link',
        sa.Column('is_primary', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_company_link', 'is_primary')
    op.alter_column('company_fact_embeddings', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('analysis_article_company_link', 'is_primary')
    # ### end Alembic commands ###
