"""add company_fact_embeddings table

Revision ID: abc3e61724a7
Revises: 8f7b4b5b59fa
Create Date: 2026-07-30 10:23:11.906810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'abc3e61724a7'
down_revision: Union[str, None] = '8f7b4b5b59fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_fact_embeddings',
    sa.Column('embedding_id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('embedding_model', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('embedding_id'),
    sa.UniqueConstraint('entity_type', 'entity_id', name='uq_company_fact_embeddings_entity')
    )
    op.create_index('ix_company_fact_embeddings_company_id', 'company_fact_embeddings', ['company_id'], unique=False)
    op.create_index('ix_company_fact_embeddings_embedding_hnsw', 'company_fact_embeddings', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_company_fact_embeddings_embedding_hnsw', table_name='company_fact_embeddings', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('ix_company_fact_embeddings_company_id', table_name='company_fact_embeddings')
    op.drop_table('company_fact_embeddings')
    # ### end Alembic commands ###
